apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mydeploy
  labels:
    service: mydeploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mydeploy
    spec:
      containers:
      - nam: main
        image: ubuntu:18.04
        command: [ "/bin/bash", "-c", "while true; do date ; sleep 1 ; done" ]
